import re

MONTHS = [
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December",
]

charge_keyword = [
    "CHARGES",
    "CHG",
    "BG CHARGES",
    "CHRGS",
    "FEE",
    "MISC",
    "MISC-REMIT",
    "BULK",
]
charge_keyword_list = "|".join(charge_keyword)

keywords = [
    "ACHDr",
    "tax",
    "ibrtgs",
    "ACCOUNT",
    "neft",
    "upi",
    "imps",
    "chq",
    "rtgs",
    "coll",
    "vps",
    "transfer",
    "paytm",
    "transferee",
    "to",
    "from",
    "by",
    "depo",
    "clearing",
    "withdrawal",
    "NEWCARDISSUE",
    "impbill",
    "trf",
    "payment",
    "chrgs",
    "remit",
    "bank",
    "ecom",
    "pos",
    "apbs",
    "chg",
    "cash",
    "cheque",
    "dd",
    "eft",
    "swift",
    "web",
    "net",
    "liq",
    "mobile",
    "tfr",
    "wdl",
    "dep",
    "deposit",
    "tds",
    "grant",
    "emi",
    "inst",
    "installment",
    "int",
    "interest",
    "pf",
    "pension",
    "deposit",
    "closure",
    "terminated",
    "ins",
    "insurance",
    "refund",
    "advtax",
    "advancetax",
    "bill",
    "CHARGES",
    "CHARGE",
    "credit",
    "debit",
    "CHG",
    "BG CHARGES",
    "CHRGS",
    "FEE",
    "MISC",
    "MISC-REMIT",
    "BULK",
    "neftcr",
]


govt_keywords = [
    "TDS",
    "GRANT",
    "REFUND",
    "TAXDEPARTMENT",
    "ADVTAX",
    "PAID",
    "ADVANCETAX",
    "EMI",
    "INSTALLMENT",
    "INST",
    "INSTALMENT",
    "PF CLOSURE",
    "PENSION CLOSURE",
    "DEPOSIT CLOSURE",
    "CLOSURE",
    "INT",
    "INTEREST",
    "INT RECEIVED",
    "INTEREST RECEIVED",
]
govt_pattern = re.compile(
    rf'(?<![a-zA-Z0-9]){ "|".join(map(re.escape, govt_keywords)) }(?![a-zA-Z0-9])',
    re.IGNORECASE,
)


keyword_list = "|".join(keywords)
keyword_pattern = re.compile(
    r"\b(?:" + "|".join(map(re.escape, keywords)) + r")\b", flags=re.IGNORECASE
)


deduct_keywords = [
    "INS",
    "INSURANCE",
    "LIFE",
    "HEALTH",
    "PROVI",
    "FUND",
    "PF",
    "SCHL",
    "SCHOOL",
    "CLG",
    "COLLEGE",
    "UNIVERSITY",
    "EDUCATIONAL INSTITUTE",
    "EDU INST",
    "STAMP DUTY",
    "REGISTRATION FEES",
    "STAMP",
    "REGISTRAR OFFICE",
    "PENSION",
    "MONEY",
    "MUTUAL",
    "FUND",
    "ASSET",
    "FINAN",
    "LIFE",
    "MEDI",
    "HOSP",
    "HOSPITAL",
    "CHECKUP",
    "BODYCHECKUP",
    "SCAN",
    "INT",
    "EDU",
    "FINAN",
    "INSTITU",
    "CHARITAB",
    "DONATION",
    "DONA",
    "TRUST",
    "HOME",
    "RENT",
    "INT",
    "HOUSE LOAN",
    "INTEREST",
    "INTREST",
    "ELECTRIC",
    "VEHICLE",
    "POLITICAL",
    "PARTY",
]
deduct_keyword_list = "|".join(deduct_keywords)
deduct_key_pattern = re.compile(
    r"\b(?:" + deduct_keyword_list + r")\b", flags=re.IGNORECASE
)

deduct_dict = {
    "80c": [
        "INS",
        "INSURANCE",
        "LIFE",
        "HEALTH",
        "PROVI",
        "FUND",
        "PF",
        "SCHL",
        "SCHOOL",
        "CLG",
        "COLLEGE",
        "UNIVERSITY",
        "EDUCATIONAL INSTITUTE",
        "EDU INST",
        "STAMP DUTY",
        "REGISTRATION FEES",
        "STAMP",
        "REGISTRAR OFFICE",
    ],
    "80ccc": ["PENSION"],
    "80ccg": ["MONEY", "MUTUAL", "FUND", "ASSET", "FINAN", "LIFE"],
    "80d/80dd": ["MEDI", "HOSP", "HOSPITAL", "CHECKUP", "BODYCHECKUP", "SCAN"],
    "80ee": [
        "INT",
        "EDU",
        "FINAN",
        "INSTITU",
        "CHARITAB",
        "INT",
        "HOUSE LOAN",
        "INTEREST",
        "INTREST",
    ],
    "80g": ["DONATION", "DONA", "TRUST", "HOME", "RENT"],
    "80eeb": ["ELECTRIC", "VEHICLE"],
    "80ggb": ["POLITICAL", "PARTY"],
}

lang_heading = {
    0: [
        ["Date", "Decription", "Amount", "Type"],
        ["Particular", "Count", "Amount INFLOW", "Amount OUTFLOW"],
        ["Date", "Decription", "Amount INFLOW", "Amount OUTFLOW"],
        ["Date", "Decription", "Amount", "Type"],
        ["Date", "Decription", "Amount", "Type"],
        ["Description", "Debit", "Credit"],
        ["Date", "Decription", "Amount"],
        ["Date", "Decription", "IN", "OUT"],
    ],
    1: [
        ["தேதி", "விளக்கம்", "தொகை", "வகை"],
        ["விளக்கம்", "எண்ணிக்கை", "வரவுத்தொகை", "செலவுத்தொகை"],
        ["தேதி", "விளக்கம்", "வரவுத்தொகை", "செலவுத்தொகை"],
        ["தேதி", "விளக்கம்", "தொகை", "வகை"],
        ["தேதி", "விளக்கம்", "தொகை", "வகை"],
        ["விளக்கம்", "செலவு", "வரவு"],
    ],
    2: [
        ["തീയതി", "വിവരണം", "തുക", "തരം"],
        ["വിവരണം", "എണ്ണുക", "തുകയുടെ വരവ്", "തുക പുറത്തേക്ക് ഒഴുകുന്നു"],
        ["തീയതി", "വിവരണം", "തുകയുടെ വരവ്", "തുക പുറത്തേക്ക് ഒഴുകുന്നു"],
        ["തീയതി", "വിവരണം", "തുക", "തരം"],
        ["തീയതി", "വിവരണം", "തുക", "തരം"],
        ["വിവരണം", "ഡെബിറ്റ്", "കടപ്പാട്"],
    ],
    3: [
        ["తేదీ", "వివరణ", "మొత్తం", "రకము"],
        ["వివరణ", "లెక్కించు", "ఇన్‌ఫ్లో మొత్తం", "అవుట్‌ఫ్లో మొత్తం"],
        ["తేదీ", "వివరణ", "ఇన్‌ఫ్లో మొత్తం", "అవుట్‌ఫ్లో మొత్తం"],
        ["తేదీ", "వివరణ", "మొత్తం", "రకము"],
        ["తేదీ", "వివరణ", "మొత్తం", "రకము"],
        ["వివరణ", "డెబిట్", "క్రెడిట్"],
    ],
    4: [
        ["तारीख", "विवरण", "मात्रा", "प्रकार"],
        ["विवरण", "गणना", "राशि का प्रवाह", "राशि का बहिर्प्रवाह"],
        ["तारीख", "विवरण", "राशि का प्रवाह", "राशि का बहिर्प्रवाह"],
        ["तारीख", "विवरण", "मात्रा", "प्रकार"],
        ["तारीख", "विवरण", "मात्रा", "प्रकार"],
        ["विवरण", "नामे", "श्रेय"],
    ],
}
