services:
  - type: web
    name: my-app
    env: docker
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: python app.py
    envVars:
      - key: LC_ALL
        value: en_US.UTF-8
      - key: LANG
        value: en_US.UTF-8
      - key: LANGUAGE
        value: en_US:en
